CFLAGS=-ggdb -Wall -std=c11
LDLIBS=-lm

all: zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5 zadanie_6 zadanie_7 zadanie_8 zadanie_10 zadanie2 funkcja

funkcja: funkcja.c myio.o myio.h

clean:
	rm -f *.o a.out myio.o zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5 zadanie_6 zadanie_7 zadanie_8 zadanie_10 zadanie2 funkcja