CFLAGS=-ggdb -Wall -std=c11
LDLIBS=-lm

all: zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5 atoi szachy zadanie_8 putchar choinka tablica tabica

clean:
	rm -f *.o zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5 atoi szachy zadanie_8 putchar choinka tablica tabica